import Head from 'next/head'
import Image from 'next/image'
import SampleButton from '@/components/Button'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.home}>
        <div>
          <p className={styles.weight300}>フォントウェイト300</p>
          <p className={styles.weight400}>フォントウェイト400</p>
          <p className={styles.weight500}>フォントウェイト500</p>
          <p className={styles.weight700}>フォントウェイト700</p>
          <SampleButton label='ボタン' size='large' />
          <SampleButton label='ボタン' size='medium' />
          <SampleButton label='ボタン' size='small' />
          <SampleButton label='ボタン' size='large' color='light' />
          <SampleButton label='ボタン' size='medium' color='light' />
          <SampleButton label='ボタン' size='small' color='light' />
        </div>
      </main>
    </>
  )
}
